"""empty message

Revision ID: 3c442bb82cd1
Revises: 77490bb2e9d8
Create Date: 2020-03-22 15:36:42.114139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c442bb82cd1'
down_revision = '77490bb2e9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cinema_user', sa.Column('is_verify', sa.Boolean(), nullable=True))
    op.drop_column('cinema_user', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cinema_user', sa.Column('permission', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('cinema_user', 'is_verify')
    # ### end Alembic commands ###
