"""empty message

Revision ID: 697ff76ae96d
Revises: 5a91cb781fa4
Create Date: 2020-03-24 12:41:42.425851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697ff76ae96d'
down_revision = '5a91cb781fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('o_user_id', sa.Integer(), nullable=True),
    sa.Column('o_hall_movie_id', sa.Integer(), nullable=True),
    sa.Column('o_time', sa.DateTime(), nullable=True),
    sa.Column('o_status', sa.Integer(), nullable=True),
    sa.Column('o_seats', sa.String(length=128), nullable=True),
    sa.Column('o_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['o_hall_movie_id'], ['hall_movie.id'], ),
    sa.ForeignKeyConstraint(['o_user_id'], ['movie_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_order')
    # ### end Alembic commands ###
