"""empty message

Revision ID: 847f0c80dbae
Revises: 3c13fb52824e
Create Date: 2020-03-23 17:09:30.603409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847f0c80dbae'
down_revision = '3c13fb52824e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('num', table_name='ciname_hall')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('num', 'ciname_hall', ['num'], unique=True)
    # ### end Alembic commands ###
