"""empty message

Revision ID: 8e4cc45a47a8
Revises: d3c37893c4f4
Create Date: 2020-03-23 09:49:00.044564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4cc45a47a8'
down_revision = 'd3c37893c4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciname_hall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('seats', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['cinema_address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ciname_hall')
    # ### end Alembic commands ###
