"""empty message

Revision ID: fdd75601b104
Revises: 016610a463a8
Create Date: 2020-03-21 21:04:38.064253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdd75601b104'
down_revision = '016610a463a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone', table_name='admin_user')
    op.drop_column('admin_user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('phone', mysql.VARCHAR(length=32), nullable=True))
    op.create_index('phone', 'admin_user', ['phone'], unique=True)
    # ### end Alembic commands ###
